// Cette constante contient le texte intégral du guide GINA 2025.
// L'assistant IA l'utilisera comme sa seule source de connaissances.
export const GINA_DOCUMENT_TEXT = `
[Le texte intégral du document GINA 2025 fourni dans l'invite de l'utilisateur serait inséré ici.
Ceci est une très grande chaîne de caractères contenant les 274 pages de texte océrisé.]

Global Strategy for Asthma Management and Prevention (2025 update)
The reader acknowledges that this report is intended as an evidence-based asthma management strategy, for the use of healthcare providers and policy-makers...
...
...
[...plusieurs pages de texte...]
...
...
989. Brusselle GG, Koppelman GH. Biologic therapies for severe asthma. N Engl J Med 2022; 386: 157-171.
`;
